import Footer from '@/layouts/Footer';
import Header from '@/layouts/Header';
import Layout from '@/layouts/Layout';
import { Container } from '@mui/material';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  fallback: ['Arial', 'Verdana', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Init App',
  description: 'Generated by Wiut students',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      suppressHydrationWarning
    >
      <body
        className={inter.className}
        suppressHydrationWarning
      >
        <NextIntlClientProvider messages={messages}>
          <Header />
          <Layout>
            <Container>{children}</Container>
          </Layout>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
